name: Rust CI

# Gatilhos: roda em pushes para a main e develop, e em pull requests para a develop
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Job para checar formatação e lints (boas práticas)
  check:
    name: Check & Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Run Clippy
        run: cargo clippy -- -D warnings # Trata warnings como erros

  # Job para rodar testes (mesmo que não tenhamos, é uma boa prática)
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose

  # Job para compilar o projeto em modo release
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build release
        run: cargo build --verbose --release