name: Rust CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    # A linha mágica está aqui.
    # Isso define o diretório de trabalho padrão para todos os passos deste job.
    defaults:
      run:
        working-directory: ./organizador_de_arquivos

    steps:
      # 1. Baixa o código do seu repositório para o runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Roda o formatador no modo de checagem
      - name: Check formatting
        run: cargo fmt -- --check

      # 3. Roda o Clippy para checar por erros e warnings
      - name: Run Clippy
        run: cargo clippy -- -D warnings

      # 4. Roda os testes
      - name: Run tests
        run: cargo test --verbose

      # 5. Compila o projeto em modo release para garantir que está funcional
      - name: Build release
        run: cargo build --verbose --release